CREATE TABLE `inactive_intern_data` (
  `id` int NOT NULL,
  `association` varchar(255) DEFAULT NULL,
  `coursename` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `fullname` varchar(255) DEFAULT NULL,
  `gradyear` date DEFAULT NULL,
  `linkedlink` varchar(255) DEFAULT NULL,
  `mentor` varchar(255) DEFAULT NULL,
  `mentoremail` varchar(255) DEFAULT NULL,
  `projectname` varchar(255) DEFAULT NULL,
  `projectstatus` int NOT NULL,
  `quarter` varchar(255) DEFAULT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `specialization` varchar(255) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `uniname` varchar(255) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `phone` int NOT NULL,
  `semester` varchar(255) DEFAULT NULL,
  `domainid` varchar(255) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

/*
-- Query: SELECT * FROM login.relnterndata
LIMIT 0, 1000

-- Date: 2024-02-02 14:52
*/
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1206,'Finance','Elvis Mayer','vixi@mailinator.com','2024-02-13','Orson Va','2023-06-27',NULL,'Madhurika','tangadisumeet@gmail.com','Shea Griffith',0,'Q1,Q2','Voluptatem enim pari','Qui accusantium dolo','Aut dolor ut autem n','2024-01-24','Isabella Sanchez',NULL,NULL,NULL,NULL,'2010-08-04','Jaime Navarro',1000000000,'48',23,'jhbcjd8t87','abcd','1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (460,'PetChem IT','Mtech','tangadisumeet@gmail.com','2023-11-24','pranav','2024-07-20','linkedin.com','pratham','pratham@gmail.com','petchem',4,'Q4','parth','ML','managment','2023-11-10','vit',NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,0,'pranav.tiwari',NULL,'0');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (552,'PetChem IT','BTech','sarangtripathi18@gmail.com','2024-01-26','Sarang Tripathi','2024-01-18','xyz','pratham','pratham@gmail.com','IMS',10,'Q1','xyz','software','comps','2024-01-24','Mumbai Univ',NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (757,'PetChem IT','BTech','sagar@gmail.com','2024-02-07','Sagar Indulkar','2024-01-17','www.linked.com','parth','xyz@gmail.com','LogBook',50,'Q3','xyz','Full Stack','Electrical Engineering','2024-01-18','Pune University',NULL,NULL,NULL,NULL,'2024-01-03','Pune',1234567890,'7',0,NULL,NULL,'0');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1502,'PetChem IT','Eleanor Clark','madicufobi@mailinator.com','2024-03-31','Thor testing','1998-11-01',NULL,'deepthi ','deepthi@gmail.com','Eagan Winters',0,'Q1,Q2,Q3,Q4','Numquam laudantium ','Nostrum reprehenderi','Ut consequatur reru','2024-02-01','Hollee English',NULL,NULL,NULL,NULL,'1976-12-26','Rashad Noel',1234567890,'81',30,NULL,NULL,'0');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1602,'Marketing','Damian Arnold','hp@mailinator.com','2024-02-15','hp charge','1986-05-31',NULL,'deepthi ','deepthi@gmail.com','Colin Hawkins',0,'Q1','Mollit molestiae sed','Rerum eiusmod et iru','Sit tenetur omnis ea','2024-01-15','Michael Hunter',NULL,NULL,NULL,NULL,'2015-07-22','Eagan Day',1234567890,'68',31,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1652,'PetChem IT','Brandon Mcdaniel','tugajyg@mailinator.com','2024-06-19','Ocean Moses','1976-11-09',NULL,'pratham','pratham@gmail.com','Habibi',0,'Q1','Do rerum consequat ','In qui omnis beatae ','Et qui autem eaque i','2024-01-11','Rae Estrada',NULL,NULL,NULL,NULL,'2011-09-14','Nehru Campbell',1234567890,'61',0,NULL,NULL,'0');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1653,'Marketing','Cora Santana','jasoly@mailinator.com','2024-09-06','Barclay Sparks','2017-05-18',NULL,'pratham','pratham@gmail.com','huiihuii',0,'Q1','Et perferendis excep','Veniam natus sapien','Consequatur deserunt','2024-04-10','Fletcher Holloway',NULL,NULL,NULL,NULL,'2006-10-21','Jarrod Drake',1234567890,'45',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1654,'HR','Len Webb','fufamy@mailinator.com','2024-03-08','Kitra Faulkner','1984-09-25',NULL,'deepthi ','deepthi@gmail.com','fiberoptics',0,'Q2','Commodi unde porro s','Asperiores et volupt','Non elit asperiores','2024-01-16','Emery Hernandez',NULL,NULL,NULL,NULL,'1976-04-09','Zane Gilmore',1234567890,'6',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1702,'PetChem IT','Mira Zimmerman','yoyo@gmail.com','2024-02-18','Idona Wallace','1970-08-31',NULL,'deepthi ','deepthi@gmail.com','Email Generator ',0,'Q1','Molestias officia si','Iure occaecat facere','Incidunt consequatu','2024-01-28','Cody House',NULL,NULL,NULL,NULL,'2003-12-15','Indigo Campos',1234567890,'100',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1703,'Finance','Kasimir Horne','1032210549@tcetmumbai.in','2024-04-08','Sybil Keith','1999-04-01',NULL,'deepthi ','deepthi@gmail.com','Judah Velasquez',0,'Q1','Eu numquam consequat','Nostrum modi omnis r','Voluptatibus archite','2024-03-02','Kareem Burch',NULL,NULL,NULL,NULL,'1981-12-23','Grace Cortez',1234567890,'88',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1704,'Marketing','Alyssa Larson','yopo@gmail.com','2024-05-29','fuzaseMarshall','1983-05-12',NULL,'Abhishek','abhishek@gmail.com','Email Generator ',0,'Q1','Dolor optio sed dol','Ut dolor doloremque ','Accusamus proident ','2024-04-30','Venus Garner',NULL,NULL,NULL,NULL,'1984-02-22','Lenore Thompson',1234567890,'75',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1705,'HR','Iona Carroll','jobita@mailinator.com','2024-06-10','Paula Owens','2014-04-22',NULL,'xyz','xyz@gmail.com','Colleen Wiggins',0,'Q1','Minima reiciendis no','Esse incididunt cor','Cum ab aut excepteur','2024-04-15','Edward Clay',NULL,NULL,NULL,NULL,'2017-09-26','Murphy Nguyen',1234567890,'55',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1752,'HR','Quin Morgan','dekywati@mailinator.com','2024-09-25','Abbot Richard','2003-10-04',NULL,'Jaydeep','jaydeep@gmail.com','Flavia Bauer',0,'Q2','Consequuntur aliqua','Facere duis sint do ','Quod rem eum odio qu','2024-08-04','Graham Wallace',NULL,NULL,NULL,NULL,'2013-02-27','Glenna Wright',1234589000,'43',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1753,'Finance','Cyrus Montoya','bilanyper@mailinator.com','2024-12-28','Raphael Bishop','1985-01-28',NULL,'Abhishek','abhishek@gmail.com','Bo Bowman',0,'Q1','Unde autem dolore ut','Cum distinctio Dele','Quis distinctio Est','2024-09-22','Jonas Guerra',NULL,NULL,NULL,NULL,'2013-05-26','Cameran Todd',1234567876,'20',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1754,'HR','Azalia Mayo','pogo@gmail.com','2024-02-09','fuzase tripathi','1976-07-27',NULL,'Jaydeep','jaydeep@gmail.com','Nina Ayala',0,'Q1','Nisi pariatur Volup','Qui hic nulla verita','Excepturi dolorem vo','2024-01-14','Chava Saunders',NULL,NULL,NULL,NULL,'2003-12-15','Malik Keller',1234567890,'35',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1802,'Finance','Drake Olsen','gopoto@gmail.com','2024-04-17','Aladdin Hampton','1978-07-29',NULL,'Jaydeep','jaydeep@gmail.com','Email',0,'Q4','Adipisicing in sed q','Cumque amet irure r','Non consequuntur tem','2024-03-26','Tara Duran',NULL,NULL,NULL,NULL,'2003-12-14','Lareina Long',1234567890,'34',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1803,'HR','Joseph Pearson','hazox@mailinator.com','1990-04-16','Cathleen Cooley','1995-03-24',NULL,'Abhishek','abhishek@gmail.com','Zane Peck',0,'Q1','Repellendus Nobis v','Culpa et et est ulla','Quia odio nisi sunt ','1974-12-07','Stone Torres',NULL,NULL,NULL,NULL,'2009-12-09','Jorden Best',1234567890,'55',0,NULL,NULL,'0');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1852,'Finance','Daphne Newman','fuzase100@gmail.com','2024-04-18','Venus Wheelie','2014-07-11',NULL,'xyz','xyz@gmail.com','Email',0,'Q2','Nesciunt soluta sit','Dolor occaecat natus','Asperiores sapiente ','2024-01-21','Fredericka Rivas',NULL,NULL,NULL,NULL,'2022-03-08','Whilemina Jefferson',1234567890,'98',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1902,'Finance','Bradley Grimes','ryqaj@mailinator.com','2024-06-28','Benjamin Wilkinson','1996-02-07',NULL,'deepthi ','deepthi@gmail.com','Whitney Mason',0,'Q2,Q3','Perspiciatis iste d','Molestiae laborum te','Voluptatibus incidid','2024-03-08','Geraldine Austin',NULL,NULL,NULL,NULL,'2019-08-12','Jakeem Serrano',1234567890,'92',0,NULL,NULL,'1');
INSERT INTO `` (`id`,`association`,`coursename`,`email`,`end_date`,`fullname`,`gradyear`,`linkedlink`,`mentor`,`mentoremail`,`projectname`,`projectstatus`,`quarter`,`reference`,`role`,`specialization`,`start_date`,`uniname`,`description`,`end`,`start`,`task`,`dob`,`location`,`phone`,`semester`,`user_id`,`domainid`,`remarks`,`is_active`) VALUES (1903,'Finance','Octavius Nieves','wijiqyqy@mailinator.com','1983-12-22','Vera Grimes','2005-05-08',NULL,'deepthi ','deepthi@gmail.com','Bernard Guzman',0,'Q1','Minus et perferendis','Sunt nesciunt debit','Hic aut nostrum odio','1989-01-20','Bree Poole',NULL,NULL,NULL,NULL,'1980-09-05','Aimee Fields',1234567888,'89',0,NULL,NULL,'0');
